### ISSUE TITLE
生成图片部分貌似有点小问题

### ISSUE THREAD

**Issue by teleaki** [Nick-bit233/mai-gen-videob50#11]
## [2/4]测试图片生成功能...
测试图片生成时发生错误:
Traceback (most recent call last):
  File "C:\Users\000\Desktop\mai-gen-videob50\test.py", line 39, in test_image_generation
    generate_single_image(
  File "C:\Users\000\Desktop\mai-gen-videob50\gene_images.py", line 11, in generate_single_image
    single_image = function.GenerateOneAchievement(record_detail)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\000\Desktop\mai-gen-videob50\utils\Utils.py", line 249, in GenerateOneAchievement
    Achievement = self.AchievementLoader(record_detail["achievements"])
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\000\Desktop\mai-gen-videob50\utils\Utils.py", line 75, in AchievementLoader
    IntegerPart = Achievement.split('.')[0]
                  ^^^^^^^^^^^^^^^^^
AttributeError: 'float' object has no attribute 'split'

https://github.com/user-attachments/assets/b70ab989-6268-4f51-8c87-1864b8ac41e0

**Comment by Nick-bit233** [comment]
已修复，参考 #9 
请使用新的v0.1.1 release包。
