### ISSUE TITLE
test.py爆400了，最好检查一下url拼接有没有bug

### ISSUE THREAD

**Issue by Flyingpigeon182** [Nick-bit233/mai-gen-videob50#15]
## [1/4]测试网络代理配置...
当前代理设置: 127.0.0.1:50242
## [3/4]测试视频搜索和下载功能...
Traceback (most recent call last):
  File "C:\Users\flyingpigeon\Downloads\mai-gen-videob50-main\test.py", line 205, in <module>
    test_system()
  File "C:\Users\flyingpigeon\Downloads\mai-gen-videob50-main\test.py", line 192, in test_system
    results = downloader.search_video("系ぎて")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\flyingpigeon\Downloads\mai-gen-videob50-main\utils\video_crawler.py", line 90, in search_video
    for result in results.videos:
                  ^^^^^^^^^^^^^^
  File "C:\Users\flyingpigeon\ANACONDA\anaconda3\envs\mai-gen-videob50\Lib\site-packages\pytubefix\contrib\search.py", line 141, in videos
    self._get_results()
  File "C:\Users\flyingpigeon\ANACONDA\anaconda3\envs\mai-gen-videob50\Lib\site-packages\pytubefix\contrib\search.py", line 122, in _get_results
    results, continuation = self.fetch_and_parse()
                            ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\flyingpigeon\ANACONDA\anaconda3\envs\mai-gen-videob50\Lib\site-packages\pytubefix\contrib\search.py", line 249, in fetch_and_parse
    raw_results = self.fetch_query(continuation,
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\flyingpigeon\ANACONDA\anaconda3\envs\mai-gen-videob50\Lib\site-packages\pytubefix\contrib\search.py", line 387, in fetch_query
    query_results = self._innertube_client.search(self.query, continuation=continuation, data=filters)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\flyingpigeon\ANACONDA\anaconda3\envs\mai-gen-videob50\Lib\site-packages\pytubefix\innertube.py", line 894, in search
    return self._call_api(endpoint, query, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\flyingpigeon\ANACONDA\anaconda3\envs\mai-gen-videob50\Lib\site-packages\pytubefix\innertube.py", line 778, in _call_api
    response = request._execute_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\flyingpigeon\ANACONDA\anaconda3\envs\mai-gen-videob50\Lib\site-packages\pytubefix\request.py", line 35, in _execute_request
    return urlopen(request, timeout=timeout)  # nosec
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\flyingpigeon\ANACONDA\anaconda3\envs\mai-gen-videob50\Lib\urllib\request.py", line 215, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\flyingpigeon\ANACONDA\anaconda3\envs\mai-gen-videob50\Lib\urllib\request.py", line 521, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\flyingpigeon\ANACONDA\anaconda3\envs\mai-gen-videob50\Lib\urllib\request.py", line 630, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "C:\Users\flyingpigeon\ANACONDA\anaconda3\envs\mai-gen-videob50\Lib\urllib\request.py", line 559, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\flyingpigeon\ANACONDA\anaconda3\envs\mai-gen-videob50\Lib\urllib\request.py", line 492, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "C:\Users\flyingpigeon\ANACONDA\anaconda3\envs\mai-gen-videob50\Lib\urllib\request.py", line 639, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400: Bad Request

**Comment by Flyingpigeon182** [comment]
使用clash of windows代理，开启了oauth并完成了设备验证

**Comment by Nick-bit233** [comment]
Close this issue due to out-dated. If any problem occurs in newer version, please post a new issue.
