### ISSUE TITLE
运行test.py报错

### ISSUE THREAD

**Issue by HESYlaowang** [Nick-bit233/mai-gen-videob50#17]
Traceback (most recent call last):
  File "/Users/admin/Downloads/mai-gen-videob50-main/test.py", line 7, in <module>
    from gene_video import create_info_segment, create_video_segment, add_clip_with_transition
  File "/Users/admin/Downloads/mai-gen-videob50-main/gene_video.py", line 5, in <module>
    from moviepy import VideoFileClip, ImageClip, TextClip, AudioFileClip, CompositeVideoClip, CompositeAudioClip, concatenate_videoclips
  File "/Users/admin/anaconda3/lib/python3.11/site-packages/moviepy/__init__.py", line 23, in <module>
    from moviepy.video.io.display_in_notebook import display_in_notebook
  File "/Users/admin/anaconda3/lib/python3.11/site-packages/moviepy/video/io/display_in_notebook.py", line 22, in <module>
    from IPython.display import HTML
  File "/Users/admin/anaconda3/lib/python3.11/site-packages/IPython/__init__.py", line 52, in <module>
    from .core.application import Application
  File "/Users/admin/anaconda3/lib/python3.11/site-packages/IPython/core/application.py", line 26, in <module>
    from IPython.core import release, crashhandler
  File "/Users/admin/anaconda3/lib/python3.11/site-packages/IPython/core/crashhandler.py", line 27, in <module>
    from IPython.core import ultratb
  File "/Users/admin/anaconda3/lib/python3.11/site-packages/IPython/core/ultratb.py", line 103, in <module>
    from pygments.formatters.terminal256 import Terminal256Formatter
  File "/Users/admin/anaconda3/lib/python3.11/site-packages/pygments/__init__.py", line 37, in <module>
    from pygments.util import StringIO, BytesIO
  File "/Users/admin/anaconda3/lib/python3.11/site-packages/pygments/util.py", line 27, in <module>
    tag_re = re.compile(r'<(.+?)(\s.*?)?>.*?</.+?>(?uism)')
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/admin/anaconda3/lib/python3.11/re/__init__.py", line 227, in compile
    return _compile(pattern, flags)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/admin/anaconda3/lib/python3.11/re/__init__.py", line 294, in _compile
    p = _compiler.compile(pattern, flags)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/admin/anaconda3/lib/python3.11/re/_compiler.py", line 743, in compile
    p = _parser.parse(p, flags)
        ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/admin/anaconda3/lib/python3.11/re/_parser.py", line 980, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/admin/anaconda3/lib/python3.11/re/_parser.py", line 455, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/admin/anaconda3/lib/python3.11/re/_parser.py", line 841, in _parse
    raise source.error('global flags not at the start '
re.error: global flags not at the start of the expression at position 24

**Comment by Nick-bit233** [comment]
看起来是导入外部包的时候出的问题，不太清楚这个错误产生的原因，不过搜索了相关报错有人提到可能是python3.11的问题，可以试试换一个3.10的python环境？使用命令`conda create -n mai-gen-videob50 python=3.10`

**Comment by Nick-bit233** [comment]
> 看起来是导入外部包的时候出的问题，不太清楚这个错误产生的原因，不过搜索了相关报错有人提到可能是python3.11的问题，可以试试换一个3.10的python环境？使用命令`conda create -n mai-gen-videob50 python=3.10`

PS：我自己用的python 3.11.10环境并未遇到该问题
